variable "vm_count" {}
variable "vm_name" {}
variable "vm_description" {}
variable "target_node" {}
variable "clone_template" {}
variable "cores" {}
variable "sockets" {}
variable "vcpus" {}
variable "memory" {}
variable "cloudinit_storage" {}
variable "disk_size" {}
variable "disk_cache" {}
variable "disk_storage" {}
variable "disk_replicate" {}
variable "network_model" {}
variable "network_bridge" {}
variable "network_tag" {}
variable "ipconfig0" {}
variable "ciuser" {}
variable "cipassword" {}
variable "ssh_public_key" {}